Repository tsparticles/vue3, pull requests merged in 2024-03, with the labels that each got.

#65 add theme prop and watcher
  components/vue3/src/components/vue-particles.vue
Labels: size/S

#68 fix: Remove particleInit event listening when a component is unmounted
  components/vue3/src/components/vue-particles.vue
Labels: size/XS

#69 3.0.1
  CHANGELOG.md
  README.md
  apps/nuxt3/CHANGELOG.md
  apps/nuxt3/package.json
  apps/vue3/CHANGELOG.md
  apps/vue3/package.json
  components/vue3/CHANGELOG.md
  components/vue3/README.md
  components/vue3/package.json
  components/vue3/src/components/vue-particles.vue
  lerna.json
  pnpm-lock.yaml
Labels: size/XXL
